taskr/config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :events
  resources :tasks
  resources :users, except: [:index]
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

end

taskr/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

taskr/app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  title      :string
#  address    :string
#  start_date :datetime
#  end_date   :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Event < ApplicationRecord
  has_many :tasks
  has_many :users, through: :tasks
  has_many :locations
end

taskr/app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id                   :integer          not null, primary key
#  name                 :string
#  description          :text
#  special_instructions :text
#  event_id             :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class Location < ApplicationRecord
  belongs_to :event
end

taskr/app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id            :integer          not null, primary key
#  title         :string
#  user_id       :integer
#  event_id      :integer
#  task_location :string
#  end_location  :string
#  description   :text
#  priority      :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Task < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many :locations
end

taskr/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  manager         :boolean
#  password_digest :string
#  email           :string
#  phone           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null

class User < ApplicationRecord
  has_many :tasks
  has_many :events, through: :tasks
  has_secure_password
  validates :email, uniqueness: true
end

taskr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in

  def home
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in
    if !!current_user
      return true
    else
      redirect_to root_path
    end
  end

end

taskr/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in, except: [:index]
  before_action :find_event, only: [:show, :edit, :update]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "you done created it~"
      redirect_to event_path(@event)
    else
      flash[:error] = "nerp!"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = "you done did it~"
      redirect_to event_path(@event)
    else
      flash[:error] = "no no no..."
      render :update
    end
  end

  def destroy
    @event.delete
    flash[:success] = "gewd jerb!"
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :address, :start_date, :end_date)
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

taskr/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if @user = User.find_by(email: params[:email]) || @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

taskr/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :signed_in, except: [:index]
  before_action :find_task, only: [:show, :edit, :update]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "you done created it~"
      redirect_to task_path(@task)
    else
      flash[:error] = "nerp!"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = "you done did it~"
      redirect_to task_path(@task)
    else
      flash[:error] = "no no no..."
      render :update
    end
  end

  def destroy
    @task.delete
    flash[:success] = "gewd jerb!"
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :task_location, :end_location, :description, :priority)
  end

  def find_task
    @task = Task.find(params[:id])
  end

end

taskr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]
  before_action :signed_in, except: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "you done created it~"
      redirect_to user_path(@user)
    else
      flash[:error] = "nerp!"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "you done did it~"
      redirect_to user_path(@user)
    else
      flash[:error] = "no no no..."
      render :update
    end
  end

  def destroy
    @user.delete
    flash[:success] = "gewd jerb!"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :manager, :password, :password_confirmation, :email, :phone)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

taskr/app/helpers/application_helper.rb
module ApplicationHelper
end

taskr/app/helpers/events_helper.rb
module EventsHelper
end

taskr/app/helpers/tasks_helper.rb
module TasksHelper
end

taskr/app/helpers/users_helper.rb
module UsersHelper
end

taskr/app/views/application/home.html.erb
<h1>YOU HOME! GET USED TO IT!</h1>

taskr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !current_user %>
    <div>
      <%= link_to "Sign In", signin_path %> || <%= link_to "Sign Up", new_user_path %>
    </div>
      <% else %>
    <div>  <%= link_to "Ma P-file", user_path(current_user) %> || <%= link_to "Sign Out", signout_path, method: :delete %>
    </div>
    <% end %>

    <%= yield %>
    <button><%= link_to "All Events", events_path %></button>
    <button><%= link_to "All Tasks", tasks_path %></button>
    <button><%= link_to "Home Page", root_path %></button>
  </body>
</html>

taskr/app/views/users/edit.html.erb
<h1>Edit!</h1>
<%=form_for(@user) do |f|%>
  <div><%=f.label :name%><%=f.text_field :name%></div>
  <div><%=f.label :email%><%=f.text_field :email%></div>
  <div><%=f.label :manager%><%=f.check_box :manager%></div>
  <div><%=f.label :phone%><%=f.telephone_field :phone%></div>
<%=f.submit "Change yo self"%>
<% end %>

taskr/app/views/users/new.html.erb
<h1>Sign Up</h1>
<%=form_for(@user) do |f|%>
  <div><%=f.label :name%><%=f.text_field :name%></div>
  <div><%=f.label :email%><%=f.text_field :email%></div>
  <div><%=f.label :manager%><%=f.check_box :manager%></div>
  <div><%=f.label :password%><%=f.password_field :password%></div>
  <div><%=f.label :password_confirmation%><%=f.password_field :password_confirmation%></div>
  <div><%=f.label :phone%><%=f.telephone_field :phone%></div>
<%=f.submit "Will self into existence"%>
<% end %>

taskr/app/views/users/show.html.erb
<div>
  <%= @user.name %>

</div>